name: 'Auto Pull Data'
on:
  schedule:
    - cron: '0 23,13 * * *' # utc+8=7,21
env:
  API_HOSTNAME: ${{ vars.API_HOSTNAME }}
  API_PREFIX: ${{ vars.API_PREFIX }}
  API_ENV: ${{ vars.API_ENV }}
  OSS_REGION: ${{ vars.OSS_REGION }}
  OSS_BUCKET: ${{ vars.OSS_BUCKET }}
  OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
  OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: log
        run: pnpm pull
